const CATEGORIES = require("../shared/constants").Categories;

const US_EMISSION_KG_PER_YEAR = {
  [CATEGORIES.BEEF]: 1352,
  [CATEGORIES.CHICKEN]: 300,
  [CATEGORIES.PORK]: 162,
  [CATEGORIES.FISH]: 36,
  [CATEGORIES.EGGS]: 69,
  [CATEGORIES.VEGETABLES]: 70,
  [CATEGORIES.FRUITS]: 26,
  [CATEGORIES.MILK]: 205,
  [CATEGORIES.CHEESE]: 372,
  [CATEGORIES.RICE]: 47,
  [CATEGORIES.COFFEE]: 86,
  [CATEGORIES.POTATOES]: 150,
  [CATEGORIES.CHOCOLATE]: 95,
  [CATEGORIES.WHEAT]: 84,
};

const EMISSION_PER_POUND = {
  [CATEGORIES.BEEF]: 23.73,
  [CATEGORIES.CHICKEN]: 2.73,
  [CATEGORIES.PORK]: 3.18,
  [CATEGORIES.FISH]: 2.27,
  [CATEGORIES.EGGS]: 2.05,
  [CATEGORIES.VEGETABLES]: 0.45,
  [CATEGORIES.FRUITS]: 0.23,
  [CATEGORIES.MILK]: 1.36,
  [CATEGORIES.CHEESE]: 9.55,
  [CATEGORIES.RICE]: 1.82,
  [CATEGORIES.COFFEE]: 8.64,
  [CATEGORIES.POTATOES]: 1.36,
  [CATEGORIES.CHOCOLATE]: 8.64,
  [CATEGORIES.WHEAT]: 0.64,
};

const WEEKLY_CONSUMPTION_DATA_POUNDS = {
  [CATEGORIES.BEEF]: 1.1,
  [CATEGORIES.CHICKEN]: 2.1,
  [CATEGORIES.PORK]: 1,
  [CATEGORIES.FISH]: 0.3,
  [CATEGORIES.EGGS]: 0.6,
  [CATEGORIES.VEGETABLES]: 3,
  [CATEGORIES.FRUITS]: 2.2,
  [CATEGORIES.MILK]: 2.9,
  [CATEGORIES.CHEESE]: 0.8,
  [CATEGORIES.RICE]: 0.5,
  [CATEGORIES.COFFEE]: 0.2,
  [CATEGORIES.POTATOES]: 2.1,
  [CATEGORIES.CHOCOLATE]: 0.2,
  [CATEGORIES.WHEAT]: 2.5,
};

module.exports = {
  EMISSION_PER_POUND,
  WEEKLY_CONSUMPTION_DATA_POUNDS,
  US_EMISSION_KG_PER_YEAR,
};
